export const projects = [
    {
        id: 0,
        name: 'Portfolio',
        synopsis: "This portfolio",
        description: 'Portfolio is a marketlpace',
        image: '/image/portfolio.webp',
        github: 'https://github.com/ezequiel-arevalo/aragoge',
        deploy: 'https://ezequiel-arevalo.github.io/aragoge/',
    },
    {
        id: 1,
        name: 'Aragoge',
        synopsis: "Es un marketplace para atletas y profesionales",
        description: 'Aragoge es un marketplace para atletas y profesionales',
        image: '/image/aragoge.webp',
        github: 'https://github.com/ezequiel-arevalo/aragoge',
        deploy: 'https://ezequiel-arevalo.github.io/aragoge/',
    },
    {
        id: 2,
        name: 'Cuevana Games',
        synopsis: "Marketplace donde se venden juegos",
        description: 'Cuevana Games marketplce of games',
        image:  '/image/cuevana-games.webp',
        github: 'https://github.com/ezequiel-arevalo/CuevanaGames',
        deploy: '',
    },
    {
        id: 3,
        name: 'ChatLand',
        synopsis: "Aplicación de chat en tiempo real",
        description: 'ChatLand APP chat in real time',
        image: '',
        github: 'https://github.com/ezequiel-arevalo/chatland',
        deploy: '',
    },
]